### PR TITLE
api created

### PR DESCRIPTION
**Pull request by eggann**

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your name and online URLs for testing.

**Comment by eggann** [comment]
Discord name 耶耶起司

測試用api:
54.243.160.74:3000/api/attractions
54.243.160.74:3000/api/attractions?page=0&keyword=溫泉

**Comment by cwpeng** [comment]
1. Response format of http://54.243.160.74:3000/api/attraction/10 is incorrect. Check API spec carefully.
2. "images" field should be an array contains image URLs separately. Your images field get 1 additional level of array in http://54.243.160.74:3000/api/attractions?page=0. And image URLs contains many redundant characters inside.

Fix issues, leave comment for me to review again.

**Comment by eggann** [comment]
api for test:
54.243.160.74:3000/api/attractions
54.243.160.74:3000/api/attractions/10
54.243.160.74:3000/api/attractions?page=0&keyword=溫泉

2 errors are fixed.

**Comment by cwpeng** [comment]
Almost done, but "images" field should be an array, not a string.

**Comment by eggann** [comment]
api for test:
54.243.160.74:3000/api/attractions
54.243.160.74:3000/api/attractions/10
54.243.160.74:3000/api/attractions?page=0&keyword=溫泉

1 error is fixed!!

**Comment by cwpeng** [comment]
Result is OK. But before merging, you should resolve conflicts shown in this page first.

**Comment by eggann** [comment]
Please help me check! Thank you!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
